In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe = pd.read_csv('20x20grid.csv',delimiter=' ')

In [3]:
dframe

   08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
0   49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 4...
1   81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 0...
2   52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 7...
3   22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 2...
4   24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 2...
5   32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 6...
6   67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 9...
7   24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 8...
8   21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 9...
9   78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 1...
10  16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 2...
11  86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 5...
12  19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 7...
13  04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 7...
14  88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 3...
15  04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 3...
16  20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 8...
17  20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 1...
18  01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 0...